' Not-ugly plantuml style defaults

' 样式定义文档: http://plantuml.com/zh/skinparam

' 手绘样式
skinparam handwritten true

' 默认字体
skinparam defaultFontName Helvetica

skinparam sequenceMessageAlign center

' 强制使用黑/白输出模式
' skinparam monochrome true

skinparam activity {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
	BorderThickness 1
}

skinparam actor {
	BackgroundColor White
	BorderColor Black
}

skinparam usecase {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
	BorderThickness 1
}

' 类图样式
skinparam class {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
	BorderThickness 1
	
	BackgroundColor<<AggregateRoot>> DarkBlue
	BackgroundColor<<Entity>> RoyalBlue
}


skinparam object {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
}

skinparam package {
	BackgroundColor White
	BorderColor Black
}

'TODO stereotype

skinparam component {
	BackgroundColor White
	InterfaceBackgroundColor White
	BorderColor Black
	InterfaceBorderColor Black
}

skinparam note {
	BackgroundColor White
	BorderColor Black
}

skinparam state {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
}

skinparam sequence {
	ArrowColor Black
	BackgroundColor White
	ParticipantBackgroundColor White
	BorderColor Black
	LifeLineBorderColor Black
	ParticipantBorderColor Black
	BoxLineColor Black
}

skinparam interface {
	BackgroundColor White
	BorderColor Black
}
